version: "3.9"

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  api:
    container_name: pokemon
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 ./src/database/ingestion.py && uvicorn src.main:api --reload --host 0.0.0.0 --port 5000  --reload-dir src/ --log-level debug"
    # depends_on:
    #   - postgres
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

networks:
  api: